Tembo CLI
tembo-io/website pull request #393
Opened 2024-03-03 18:26 UTC by sjmiller609

2024-03-05 00:54 UTC, DarrenBaldwin07 commented on landing/src/content/blog/2024-03-08-tembo-cli/index.md
> +title: 'Announcing the Tembo CLI'
Might be nice to use "entire" in here too - lots of tools to run postgres locally but not with extensions 

"Announcing Tembo CLI: Infrastructure as code for the entire Postgres ecosystem"

2024-03-06 03:02 UTC, xenophenes requested changes
Initial review of blogpost

2024-03-06 03:39 UTC, sjmiller609 commented on landing/src/content/blog/2024-03-08-tembo-cli/index.md
> +The above **tembo.toml** file includes one database. For additional information on how your **tembo.toml** file can be configured, please see "[Configure Tembo CLI](https://tembo.io/docs/tembo-cloud/
maybe should link to examples instead, either here https://tembo.io/docs/tembo-cloud/Tembo-CLI/Examples/nextjs or here https://github.com/tembo-io/tembo/tree/main/tembo-cli/examples or combo

2024-03-06 03:41 UTC, sjmiller609 commented on landing/src/content/blog/2024-03-08-tembo-cli/index.md
> +```
maybe should indicate what it's like to connect to them locally
```
psql postgres://...@vector-search.local.tembo.io
psql postgres://...@analytics.local.tembo.io
```

2024-03-06 03:43 UTC, sjmiller609 commented
todo: replace illustration with new from design

2024-03-06 06:10 UTC, samay-sharma approved these changes
Left 2 minor comments, but after addressing them and updating the image and the date, @sjmiller609 feel free to merge whenever you think other stuff is ready to go.

2024-03-06 06:10 UTC, samay-sharma commented on landing/src/content/blog/2024-03-08-tembo-cli/index.md
> +# Announcing Tembo CLI: Infrastructure as code for the Postgres ecosystem
Remove this. The title gets repeated twice.

2024-03-08 04:36 UTC, merged