blog: add announcement post for Postgres 14 and 16 support
tembo-io/website pull request #400
Opened 2024-03-06 19:54 UTC by vrmiguel

2024-03-06 19:56 UTC, DarrenBaldwin07 commented on landing/src/content/config.ts
> +	vini: {
Nice!

2024-03-06 19:56 UTC, DarrenBaldwin07 commented on landing/src/content/blog/2024-03-06-postgres-14-and-16/index.md
> +image: './pg-14-16.png'
This image to work in our meta tags needs to be also duplicated inside of the `/public` dir here: https://github.com/tembo-io/website/tree/main/landing/public

2024-03-06 20:05 UTC, vrmiguel commented on landing/src/content/blog/2024-03-06-postgres-14-and-16/index.md
> +image: './pg-14-16.png'
Oh good catch! :rocket:

2024-03-06 21:19 UTC, DarrenBaldwin07 approved these changes

2024-03-11 23:47 UTC, samay-sharma commented on landing/src/content/blog/2024-03-06-postgres-14-and-16/index.md
> +# Announcing support for Postgres 16 and 14 on Tembo
I think we should restructure this to something like:

We're thrilled to announce ... 

Starting today, you should be able to pick from PG 14,15,16 while creating a Tembo Cloud instance [screenshot].

**Postgres 16 features**

current section

**Postgres 14 compatibility for simpler migration**

Something like:
Several users still use Postgres 14 and we received request from users to add support for this to make it easy for them to migrate.

**Expanding extension support for PG 14 and 16.**

In addition to just adding support for a new PG version, we now added the ability to trunk (link) to build extensions for different versions. One or two lines more about this.

You can find the list of all supported extensions for each version _here_. 

So, now, each of those Postgres versions comes with a wide number of supported extensions. I would suggest to show number of supported extensions by version in a table. We've also added automated testing to Tembo Cloud to ensure successful deployment of these extensions.

**Try it and join the herd**

2024-03-11 23:47 UTC, samay-sharma commented on landing/src/content/blog/2024-03-06-postgres-14-and-16/index.md
> +# Announcing support for Postgres 16 and 14 on Tembo
Overall feedback:
* reduce repetition
* Add some elements such as a table.
* Make the extensions supported thing a bit more richer.
* Add a lot of links

2024-03-13 22:39 UTC, samay-sharma commented
made a quick pass of edits. Sarah, can you do a quick pass and then we can merge?

2024-03-14 22:14 UTC, xenophenes requested changes
Hey! Here's my requested changes, main thing would be to adjust the merge or copy/paste errors where the beginning section is repeated, thanks!

2024-03-14 22:14 UTC, xenophenes commented on landing/src/content/blog/2024-03-06-postgres-14-and-16/index.md
> +We're thrilled to announce the addition of support for Postgres versions 14 and 16 in Tembo Cloud. This is a big leap forward for us. We're all in on our commitment to give developers and businesses
Suggest rephrase to:

> We're thrilled to announce the addition of support for Postgres versions 14 and 16 in Tembo Cloud. This is a big leap forward for us and builds on our commitment to empower developers and businesses to choose from the best, most powerful, and adaptable database options out there.

2024-03-14 22:14 UTC, xenophenes commented on landing/src/content/blog/2024-03-06-postgres-14-and-16/index.md
> +Whether you're building complex applications, managing large datasets, or developing cutting-edge services, the choice between Postgres 14, 15, and 16 means you can select the version that best fits
Add a sentence following to transition - something like

> Let's look further at the newest features that have been introduced to help you in making that decision.

2024-03-14 22:14 UTC, xenophenes commented on landing/src/content/blog/2024-03-06-postgres-14-and-16/index.md
> +- **Enhanced Security Features**: Enjoy stronger security measures, providing peace of mind with more robust data protection and access control.
Add something like this at the end to link out to the release notes for devs

> These and many more features have been added in the latest release! For more information, please reference the [Release Notes](https://www.postgresql.org/docs/current/release-16.html).

2024-03-14 22:14 UTC, xenophenes commented on landing/src/content/blog/2024-03-06-postgres-14-and-16/index.md
> +- # Announcing support for Postgres 16 and 14 on Tembo
Looks like you unintentionally added this section in there twice? Have redundant information

2024-03-14 22:14 UTC, xenophenes commented on landing/src/content/blog/2024-03-06-postgres-14-and-16/index.md
> +These enhancements, along with many others, ensure that Postgres 16 is not just an update but a significant advancement in database technology.
This section looks better written compared to the first. Maybe there was a problem with a merge. Either way, this looks better - still would add the link to the release notes at the end

2024-03-14 22:14 UTC, xenophenes commented on landing/src/content/blog/2024-03-06-postgres-14-and-16/index.md
> +At Tembo, we're proud to offer a wide array of extensions to enhance the capabilities of your Postgres instances. With 203 extensions for Postgres 15, 180 for Postgres 14, and 147 currently available
Aren't these all provided through Trunk? And isn't Trunk free for anyone to use, regardless of if they're using Tembo? If so, should link out to Trunk here

2024-03-14 22:14 UTC, xenophenes commented on landing/src/content/blog/2024-03-06-postgres-14-and-16/index.md
> +
Is there somewhere a dev could ask when support will be added? Slack, GitHub recommended? Discord? Reference it here so users can feel empowered to create a discussion around adding support sooner rather than later for something specific

2024-03-14 22:14 UTC, xenophenes commented on landing/src/content/blog/2024-03-06-postgres-14-and-16/index.md
> +Sign up for free today and discover how our platform can revolutionize your data strategy. "Your feedback is invaluable to us — together, we're not just building a service; we're shaping the future o
There's an unexpected quotation here: `"Your feedback ...`

2024-03-14 22:14 UTC, xenophenes commented on landing/src/content/blog/2024-03-06-postgres-14-and-16/index.md
> +Stay tuned for more updates, and as always, happy coding!
Totally unnecessary, & a personal preference, but you could  add 🐘 after "...happy coding!" to personalize it further (reduce formality further between dev & writer/company while still keeping it practical/conversational throughout article)

2024-03-14 22:40 UTC, xenophenes requested changes

2024-03-14 22:40 UTC, xenophenes commented on landing/src/content/blog/2024-03-06-postgres-14-and-16/index.md
> +For more information, you can refer to the [Postgres 16 release notes](https://www.postgresql.org/docs/current/release-16.html) or our blog about [it's exciting features](https://tembo.io/blog/postgr
> or our blog about its exciting features

it's -> its

2024-03-14 22:40 UTC, xenophenes commented on landing/src/content/blog/2024-03-06-postgres-14-and-16/index.md
> +A lot of Postgres users are still using Postgres 14. Given that major Postgres versions aren't always compatible, upgrading Postgres versions is not always straightforward. Therefore, adding Postgres
"...adding Postgres 14 was one of the most commonly requested features."

where? I would assume Tembo Cloud, but this is written to where it's not specific. The last two sentences are also unrelated. Recommend rephrasing to

> Therefore, adding Postgres 14 has been one of our most commonly requested features for Tembo Cloud. Now, users can easily migrate their workloads onto the platform. 
> 
> For more information about the Postgres 14 release, including added features and bug fixes, reference the release notes [here]().

2024-03-14 22:40 UTC, xenophenes commented on landing/src/content/blog/2024-03-06-postgres-14-and-16/index.md
> +Here's a quick overview of the number of extensions supported on Tembo Cloud by each Postgres version, as of March 13th, 2024, but we're always adding more!
for clarity, 

> Here's a quick overview of the number of extensions supported on Tembo Cloud by each Postgres version (as of March 13th, 2024) but we're always adding more!

2024-03-14 22:40 UTC, xenophenes commented on landing/src/content/blog/2024-03-06-postgres-14-and-16/index.md
>  To complement the introduction of new Postgres versions, we've expanded our extension ecosystem. This includes the ability to link and build extensions for different Postgres versions, enhancing the
This entire Extension Support section seems disconnected. You talk about how "our extension ecosystem" is expanded, and then reference Trunk at the end for users to learn more about Postgres extensions. 

Up here, Trunk should be mentioned straightaway:

> To complement the introduction of new Postgres versions, we've expanded our extension ecosystem, [Trunk](https://pgt.dev). Feature additions include the ability to link and build extensions for different Postgres versions, enhancing the flexibility and capability of your databases.

Later, tie it in by rephrasing the link to Trunk in a manner like this:

> Browse our free and open source PostgreSQL extension project, [Trunk](https://pgt.dev), to learn more.

2024-03-15 17:59 UTC, sjmiller609 commented on landing/src/content/blog/2024-03-06-postgres-14-and-16/index.md
> +Here's a quick overview of the number of extensions supported on Tembo Cloud by each Postgres version, as of March 13th, 2024, but we're always adding more!
Also add a comma like this

> Here's .... (as of March 13th, 2024), but we're always adding more!

2024-03-15 18:00 UTC, sjmiller609 commented on landing/src/content/blog/2024-03-06-postgres-14-and-16/index.md
> +Here's a quick overview of the number of extensions supported on Tembo Cloud by each Postgres version, as of March 13th, 2024, but we're always adding more!
since I think this would have a comma?

> Here's a quick overview of the number of extensions supported on Tembo Cloud by each Postgres version, but we're always adding more!

2024-03-15 18:02 UTC, sjmiller609 commented on landing/src/content/blog/2024-03-06-postgres-14-and-16/index.md
> +Here's a quick overview of the number of extensions supported on Tembo Cloud by each Postgres version, as of March 13th, 2024, but we're always adding more!
not sure, going for it, lmk if otherwise

2024-03-15 18:04 UTC, sjmiller609 commented on landing/src/content/blog/2024-03-06-postgres-14-and-16/index.md
>  To complement the introduction of new Postgres versions, we've expanded our extension ecosystem. This includes the ability to link and build extensions for different Postgres versions, enhancing the
also minor editorial here, we don't want to call Trunk "our" ecosystem, since it's intended to be a community project.

> ... we've expanded the extension ecosystem in Trunk. ...

2024-03-15 18:06 UTC, sjmiller609 commented on landing/src/content/blog/2024-03-06-postgres-14-and-16/index.md
>  To complement the introduction of new Postgres versions, we've expanded our extension ecosystem. This includes the ability to link and build extensions for different Postgres versions, enhancing the
> Browse the free  ...

2024-03-15 18:08 UTC, sjmiller609 approved these changes

2024-03-15 18:45 UTC, samay-sharma approved these changes

2024-03-15 18:47 UTC, merged