Add Pause/Resume/Rename blog post
tembo-io/website pull request #593
Opened 2024-07-23 21:22 UTC by FloorD

Blog post about pausing and resuming instances, and renaming instances and organisations. 
- Thanks @sjmiller609 for reviewing
- Is missing a header image (requested)

2024-07-24 04:55 UTC, samay-sharma requested changes
Left a few comments, @FloorD . Once you address these, can do a final round and approve. Please apply any general feedback to the spot post too if you think it relevant. I'll review that one too tomorrow once you've done a round.

2024-07-24 04:55 UTC, samay-sharma commented on src/content/blog/2024-07-25-instance-advanced-options/index.mdx
> +title: 'Introducing advanced features for more flexibility'
Let's use the newspaper headline style for the title, so that people understand what's being covered. So, I'd say let's hint about what features are covered.

Some ideas:
* Introducing pause and rename for your Tembo Cloud instances
* Pause and Rename your Tembo Cloud instances for additional flexibility

2024-07-24 04:55 UTC, samay-sharma commented on src/content/blog/2024-07-25-instance-advanced-options/index.mdx
> +    Profit from new Tembo Cloud functionality to rename, pause, and resume instances
%s/Profit/Benefit

2024-07-24 04:55 UTC, samay-sharma commented on src/content/blog/2024-07-25-instance-advanced-options/index.mdx
> +We've recently added functionality to Tembo Cloud, including the ability to rename and to temporarily pause instances, to give you greater control.
Would like a slightly warmer intro into the post.

While we're enthusiastic about our big launches and features, we love to ship relatively smaller features which make our customers' life better. We're excited to add commonly requested features like the ability to rename and pause instances (when not in use) to give you greater control.

2024-07-24 04:55 UTC, samay-sharma commented on src/content/blog/2024-07-25-instance-advanced-options/index.mdx
> +## Rename Instances and Orgs
Let's motivate why people would want to do this. Some reasons I can think of:

* You often start using an instance for a particular purpose and then over time rename to better represent the use case.
* New naming conventions come by.
* A PoC instance moved to become a prod instance.
* OR you just made a typo and want to fix it.

Previously, as a user, you couldn't rename your instances to address these use cases.

2024-07-24 04:55 UTC, samay-sharma commented on src/content/blog/2024-07-25-instance-advanced-options/index.mdx
> +![Renaming your instance](./renaming-organization.png)
Images are wrong? We should have rename instance here.

2024-07-24 04:55 UTC, samay-sharma commented on src/content/blog/2024-07-25-instance-advanced-options/index.mdx
> +![Renaming your Organization](./renaming-instance.png)
Rename organization should be here.

2024-07-24 04:55 UTC, samay-sharma commented on src/content/blog/2024-07-25-instance-advanced-options/index.mdx
> +Renaming your instance will not cause downtime. Your instance will go into the Configuring status, and once the instance is successfully updated, you will receive a notification confirming the update
We should also clarify that renaming an instance will not require users to update their connection string. So, their existing connections continue to work as it is.

2024-07-24 04:55 UTC, samay-sharma commented on src/content/blog/2024-07-25-instance-advanced-options/index.mdx
> +AAnother new feature allows you to pause your Tembo Cloud instances when they are not being used actively. This way you can save costs when you're running experiments or benchmarks.
Let's improve motivation for this feature too.

We often receive requests from users who ask to pause their Tembo Cloud instances when they are not being used actively. (Please rewrite the rest from bullet points below)

Use cases where this is most relevant:
* Benchmarking on large instances which you don't want to run throughout the night or weekend.
* When you are experimenting with or migrating to the service and want to use instances only for a while.
* Setting up relatively less used environments which are very time consuming to set up.

2024-07-24 04:55 UTC, samay-sharma commented on src/content/blog/2024-07-25-instance-advanced-options/index.mdx
> +For your Organization’s name, that is found in Organization settings, which is located by clicking your profile icon in the top right of the screen.
The instructions sections read a bit dry for some reason. Can we add some bolds, underlines or italics to make visually a bit more diverse.

2024-07-25 13:21 UTC, FloorD commented on src/content/blog/2024-07-25-instance-advanced-options/index.mdx
> +We've recently added functionality to Tembo Cloud, including the ability to rename and to temporarily pause instances, to give you greater control.
I want to avoid over-using the word "excited". I will take some of the suggestions from your follow up comment.

2024-07-25 14:10 UTC, FloorD commented
Great feedback, @samay-sharma

2024-07-30 06:24 UTC, samay-sharma approved these changes

2024-07-30 06:25 UTC, samay-sharma commented
@sjmiller609 : Can you please give this a quick 2 min read and see if it looks good to you? Just want a quick proof-read after my changes before I merge once I have the design images.

2024-07-30 15:52 UTC, sjmiller609 approved these changes
All suggestions optional

2024-07-30 15:52 UTC, sjmiller609 commented on src/content/blog/2024-07-25-instance-advanced-options/index.mdx
> +We've recently added functionality to [Tembo Cloud](https://cloud.tembo.io/), including the ability to rename and to temporarily pause instances, to give you greater control. Let's dive in to learn m
```suggestion
We've recently added functionality to [Tembo Cloud](https://cloud.tembo.io/), including the ability to rename and temporarily pause instances, to give you greater control. Let's dive in to learn more about these features!

```

2024-07-30 15:52 UTC, sjmiller609 commented on src/content/blog/2024-07-25-instance-advanced-options/index.mdx
> +To change the instance name, go into _Settings_, click on the _Name_ field and enter the new name for your instance.
```suggestion
To change the instance name, go into _Settings_, click on the _Name_ field, and enter the new name for your instance.

```

2024-07-30 15:52 UTC, sjmiller609 commented on src/content/blog/2024-07-25-instance-advanced-options/index.mdx
> +Renaming your instance will not cause downtime. Your instance will go into the Configuring status, and once the instance is successfully updated, you will receive a notification confirming the update
```suggestion
Renaming your instance will not cause downtime. Your instance will go into the Configuring status, and once the instance is successfully updated, you will receive a notification confirming the update. Your instances continue to have the same connection string after a rename, meaning your applications do not need to reconnect or update their connection strings.

```

2024-07-30 15:52 UTC, sjmiller609 commented on src/content/blog/2024-07-25-instance-advanced-options/index.mdx
> +Another new Tembo Cloud feature allows you to [pause your instances](https://tembo.io/docs/product/cloud/configuration-and-management/pause-instance) when they are not being used actively. Paused ins
```suggestion
Another new Tembo Cloud feature allows you to [pause your instances](https://tembo.io/docs/product/cloud/configuration-and-management/pause-instance) when they are not being used actively. Paused instances are not [billed](https://tembo.io/docs/product/cloud/billing) for compute, but only for storage. This way, you can save costs when you're running experiments or benchmarks during the week that can be turned off during the weekend, or similar ephemeral use cases.

```

2024-07-30 15:52 UTC, sjmiller609 commented on src/content/blog/2024-07-25-instance-advanced-options/index.mdx
> +To pause an instance, go into Settings, and in Instance Settings select Pause Instance.
```suggestion
To pause an instance, go into Settings, and in Instance Settings, select Pause Instance.
```

2024-07-30 15:52 UTC, sjmiller609 commented on src/content/blog/2024-07-25-instance-advanced-options/index.mdx
> +To resume an instance, go into Settings, and in Instance Settings select Resume Instance.
```suggestion
To resume an instance, go into Settings, and in Instance Settings, select Resume Instance.
```

2024-07-30 15:52 UTC, sjmiller609 commented on src/content/blog/2024-07-25-instance-advanced-options/index.mdx
> +You can also pause instances with the [Tembo Cloud API](https://tembo.io/docs/development/api), using the [Lifecycle Events endpoint](https://api.tembo.io/redoc#tag/instance/operation/instance_event)
```suggestion
You can also pause instances with the [Tembo Cloud API](https://tembo.io/docs/development/api) using the [Lifecycle Events endpoint](https://api.tembo.io/redoc#tag/instance/operation/instance_event).
```

2024-07-31 13:53 UTC, sjmiller609 commented
re-dated and added header image, so we can ship today

2024-07-31 14:01 UTC, merged