New blog post about pg-timeseries columnar storage
tembo-io/website pull request #600
Opened 2024-07-30 17:11 UTC by bonesmoses

This is a follow-up to the Chicago Postgres User Group presentation on pg-timeseries to cover a question about how columnar storage performs. It was an interesting result that deserved further exploration.

Includes performance graphs as well as associated code in a subdirectory for reproduction purposes.

2024-08-14 11:54 UTC, FloorD approved these changes

2024-08-14 19:28 UTC, bonesmoses commented
What date should we move this to? Obviously we can't do it on the 2nd anymore. ;)

2024-09-07 18:16 UTC, jasonmp85 reviewed
High level: I found tying this discussion to `pg_timeseries` a little confusing… the intent of using columnar storage in a time-series data set is to compress _old_, non-live partitions as they age out, such that aggregation over them is faster, or perhaps they take up less space.

I would go as far as to say that having a column-oriented partition as still-receiving-updates partition is the sort of thing we would immediately flag as non-ideal if someone asked us to look at their system.

This post does a good job of showing that `INSERT`/`UPDATE`/`DELETE` can still be performed admirably with columnar storage, but because this underlying tension wasn't addressed up-front, I kept wondering who the performance benefits ("shouldn't the columnar partitions be used for old data, only?")

I assume this was maybe part of the Chicago discussion, but some introductory material pointing out that, hey, the "move to column as it ages" approach is intended, but you're examining performance  in case users decide to use it as a primary write surface, anyhow?

2024-09-07 18:16 UTC, jasonmp85 requested changes
(See comments)

2024-09-07 18:17 UTC, jasonmp85 commented
One final thing: the axes on the charts are insufficient. One just says "milliseconds", though I don't know for what (I assume individual row DML statements?), and the other has no label at all, but just many large numbers (I assume this is "extant rows in table"?)…

2024-09-07 19:53 UTC, bonesmoses commented on src/content/blog/2024-08-02-columnar-heap-write-performance/index.mdx
> +  * A separate function for inserts, updates, and deletes.
Fixed.

2024-09-07 19:54 UTC, bonesmoses commented on src/content/blog/2024-08-02-columnar-heap-write-performance/index.mdx
> +All code used for these tests is available in [this github directory](https://github.com/tembo-io/website/tree/main/src/content/blog/2024-08-02-columnar-heap-write-performance/_code) rather than inli
Fixed.

2024-09-07 19:59 UTC, bonesmoses commented on src/content/blog/2024-08-02-columnar-heap-write-performance/index.mdx
> +We should begin with the test table. Since the demonstration at the talk used the Chicago Divvy data, we elected to mimic that data for these tests as well. It presumably models a real-world use case
This is false. The fake data generated for these tests _is not_ from the Divvy data, it _mimics_ the Divvy data. Regardless, I reworded for clarity.

2024-09-07 20:03 UTC, bonesmoses commented on src/content/blog/2024-08-02-columnar-heap-write-performance/index.mdx
> +The data we collected used the same parameters as in the above example: 20 samples at 250k rows per step, for a total maximum of 5M rows on the last iteration. We split the results into inserts, upda
It seems a pointless endeavor. Does the reader not know how to multiply?

2024-09-07 20:08 UTC, bonesmoses commented on src/content/blog/2024-08-02-columnar-heap-write-performance/index.mdx
> +Columnar performance is still better, but not by much. This shouldn't really come as a huge surprise as columnar storage isn't really meant to be updated since it's designed for ingesting time-series
I reworded the whole paragraph.

2024-09-07 20:17 UTC, bonesmoses commented on src/content/blog/2024-08-02-columnar-heap-write-performance/index.mdx
> +The use of `enable_ts_table` is purely for convenience. This causes `pg_timeseries` to create all extensions from the beginning of 2020 until now. That will allow up to four years of data with `start
I considered it initially, but the sentence felt too long.

2024-09-13 16:36 UTC, jasonmp85 commented on src/content/blog/2024-08-02-columnar-heap-write-performance/index.mdx
> +The data we collected used the same parameters as in the above example: 20 samples at 250k rows per step, for a total maximum of 5M rows on the last iteration. We split the results into inserts, upda
Well, I had that thought when I saw it spelled out like this, yes.

2024-09-13 16:50 UTC, jasonmp85 commented on src/content/blog/2024-08-02-columnar-heap-write-performance/index.mdx
> +The data we collected used the same parameters as in the above example: 20 samples at 250k rows per step, for a total maximum of 5M rows on the last iteration. We split the results into inserts, upda
It's not about the reader, but rather that "5M" is not an abbreviation for "five million" in most style guides. AP suggests it only in headlines, and even then most financial writers would prefer "$5MM" because of the ambiguity with "mille" in various romance languages. Seems casual, best to avoid abbreviations in official writing.

2024-09-13 16:55 UTC, bonesmoses commented on src/content/blog/2024-08-02-columnar-heap-write-performance/index.mdx
> +The data we collected used the same parameters as in the above example: 20 samples at 250k rows per step, for a total maximum of 5M rows on the last iteration. We split the results into inserts, upda
It's a _blog_, not War and Peace.

2024-09-13 16:56 UTC, jasonmp85 commented on src/content/blog/2024-08-02-columnar-heap-write-performance/index.mdx
> +The data we collected used the same parameters as in the above example: 20 samples at 250k rows per step, for a total maximum of 5M rows on the last iteration. We split the results into inserts, upda
I don't distinguish, but sure, fine.

2024-09-13 16:58 UTC, jasonmp85 approved these changes
Reads a bit cleaner now, graphs much improved, ship it!

2024-09-13 16:58 UTC, bonesmoses commented on src/content/blog/2024-08-02-columnar-heap-write-performance/index.mdx
> +The data we collected used the same parameters as in the above example: 20 samples at 250k rows per step, for a total maximum of 5M rows on the last iteration. We split the results into inserts, upda
Regardless, if you actually looked at the changes rather than this outdated conversation, you'd see that I made the change _anyway_.

2024-09-13 17:01 UTC, jasonmp85 commented on src/content/blog/2024-08-02-columnar-heap-write-performance/index.mdx
> +The data we collected used the same parameters as in the above example: 20 samples at 250k rows per step, for a total maximum of 5M rows on the last iteration. We split the results into inserts, upda
😞 sorry. I approved the PR anyhow

2024-09-13 17:20 UTC, bonesmoses commented on src/content/blog/2024-08-02-columnar-heap-write-performance/index.mdx
> +The data we collected used the same parameters as in the above example: 20 samples at 250k rows per step, for a total maximum of 5M rows on the last iteration. We split the results into inserts, upda
I didn't mean to sound snooty. I forgot to end that last reply with "lol". :(

2024-09-16 22:52 UTC, samay-sharma reviewed
@bonesmoses : I read it and I have one major feedback. That feedback is that we spend a lot of time describing the test harness and benchmarking procedure as opposed to the results of the benchmark.

I have a proposed structure to make it shorter and more focussed on the results. Once you incorporate that, I think it's mostly good.

2024-09-16 22:52 UTC, samay-sharma commented on src/content/blog/2024-08-02-columnar-heap-write-performance/index.mdx
> +Tembo were recently invited to do a short presentation of the [pg_timeseries](https://github.com/tembo-io/pg_timeseries) extension to the [Chicago Postgres User Group](https://www.meetup.com/chicago-
Last month, Tembo was invited to ...

2024-09-16 22:52 UTC, samay-sharma commented on src/content/blog/2024-08-02-columnar-heap-write-performance/index.mdx
> +## Building the Benchmark
@bonesmoses : I found myself getting impatient to see the results of the benchmark :). The post spends more time on how we setup the benchmark as opposed to answer to the question we started with i.e. How does write performance change with heap vs columnar?

We should combine the Building the Benchmark, Starting Tables, Storage Status and To the Races into like 3-4 paragraphs so that we can get to the meat sooner.

I'd propose a structure like below. If you feel like the other sections are important I'd write a procedure.md and link to it in github so that people can read all the details if they like but I don't think some of the sections (eg. code to convert the partitions, checking storage status or the example to provide avg execution) add to the story we're trying to tell here.

----Proposal----

# Benchmarking procedure

Any proper benchmark needs a testing procedure. We performed a few simple test runs which showed interesting results, but these initial findings were soon erased once the more objective and standardized process emerged.

All code used for these tests is available in [this GitHub directory](https://github.com/tembo-io/website/tree/main/src/content/blog/2024-08-02-columnar-heap-write-performance/_code) rather than inline with the blog. Including it here would be somewhat distracting, as it’s a lot of code. But we can explore the function names, if only for amusement sake. The process works like this:

Create the divvy_trips partition tables.
Create the sample_data table to hold test results.
Create the chungus table to contain generated test data.
Execute sp_run_tests to run all of the tests, which will:
Call sp_set_storage to start with heap storage.
For the requested test count and chunk size:
Call sp_scale_chungus to generate data for that test iteration chunk size.
Truncate the divvy_trips table.
Call sp_insert_test for insert timings.
Call sp_update_test for update timings.
Call sp_delete_test for delete timings.
Repeat all insert, update, delete tests 5 times for accuracy.
Repeat entire test process for columnar storage.
Wait.
Yes, the data staging table is named chungus; depending on the requested chunk size, it can be pretty hefty. Truth in advertising is important after all!

The schemas of the relevant tables are:

divvy_tables, enable_ts_table, chungus definitions and reasoning (2 paragraphs)

# Running the benchmark

We created a function `function name` to swap partitions between heap and columnar.

Using our function, we can run our tests using however many chunks and iterations as we desire. For example:

`CALL sp_run_tests(20, 250000);`

This would run 20 tests starting at 250,000 rows and ending at five million rows (250,000 * 20). This lets us see if row count affects timings and to what extent. The results are categorized by row count, storage type, and write action, so we can slice and dice it several different ways as well.

# Performance explored
...
-----------------------------------

The above is just copy pasted from current sections so may need some massaging but I think this will be more interesting to the audience.

2024-09-16 22:52 UTC, samay-sharma commented on src/content/blog/2024-08-02-columnar-heap-write-performance/index.mdx
> +title: 'Comparing Columnar to Heap Performance in pg_timeseries'
Title suggestions: `Comparing Columnar to Heap Performance in Postgres ft. pg_timeseries

2024-09-25 20:21 UTC, bonesmoses commented on src/content/blog/2024-08-02-columnar-heap-write-performance/index.mdx
> +title: 'Comparing Columnar to Heap Performance in pg_timeseries'
I've revised this to "in Postgres with pg_timeseries".

2024-09-25 20:21 UTC, bonesmoses commented on src/content/blog/2024-08-02-columnar-heap-write-performance/index.mdx
> +## Building the Benchmark
I've made all of these changes. Code and all related content is now moved to the [Tembo Labs](https://github.com/tembo-io/tembo-labs) repo.

2024-10-10 15:49 UTC, merged